options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/task-management-backend'
      - './task-management-backend'

images:
  - 'gcr.io/$PROJECT_ID/task-management-backend'
