steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/task-management-backend:$COMMIT_SHA'
      - './task-management-backend'
images:
  - 'gcr.io/$PROJECT_ID/task-management-backend:$COMMIT_SHA'
