version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: 34.171.0.140
      DB_PORT: 5432
      DB_DATABASE: task_management
      DB_USERNAME: postgres
      DB_PASSWORD: XPgID+lIKOYRmv0h
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"   # Cloud Run escuta na porta 8080
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
